language: go
go:
        - 1.3

install:
        - go get github.com/tools/godep
        - godep restore
        - ln -s /home/travis/gopath/src/github.com/mailgun/vulcand /home/travis/gopath/src/github.com/porjo/vulcand
script:
        - go test -v ./...
